---
# ansible-playbook -i hosts vote.yml -vv
- name: runnig vote.huming.me
  hosts: vote.huming.me
  tasks:
    - name: Download docker
      tags:
        - install
        - install_docker
      get_url: url=https://get.docker.com/rpm/1.7.0/centos-6/RPMS/x86_64/docker-engine-1.7.0-1.el6.x86_64.rpm dest=/tmp/docker-engine-1.7.0-1.el6.x86_64.rpm

    - name: Install docker
      tags:
        - install
        - install_docker
      yum: name=/tmp/docker-engine-1.7.0-1.el6.x86_64.rpm disable_gpg_check=yes state=present

    - name: Start docker
      tags:
        - configure
        - configure_docker
      service: name=docker state=started enabled=yes

    # - name: use docker mirror
    #   tags:
    #     - configure
    #   template: src=sysconfig.docker dest=/etc/sysconfig/docker
    #   notify:
    #     - restart docker

  # handlers:
  #   - name: restart docker
  #     service: name=docker state=restarted
