default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  timeout: 5000
  template: template0

development:
  <<: *default
  encoding: unicode
  database: vote_dev
  pool: 5
  username: huming
  password:
  host: <%= ENV['DB_1_PORT_5432_TCP_ADDR'] %>

test:
  <<: *default
  encoding: unicode
  database: vote_test
  pool: 5
  username: huming
  host: <%= ENV['DB_1_PORT_5432_TCP_ADDR'] %>

production:
  <<: *default
  encoding: unicode
  database: vote_prod
  pool: 5
  username: postgres
  host: <%= ENV['DB_1_PORT_5432_TCP_ADDR'] %>